---
# tasks file for ossec-wazuh

- include: RedHat.yml
  when: ansible_os_family == "RedHat"

- include: install.yml

- include: api.yml
  when: ossec_wazuh_api

- include: integrator.yml
  when: ossec_wazuh_integrator

- include: localrules.yml
